# Generated by Django 4.2.13 on 2024-05-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_type',
            new_name='GameType',
        ),
    ]
