# Generated by Django 4.1.3 on 2024-05-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events_attending', through='levelupapi.EventGamer', to='levelupapi.gamer'),
        ),
    ]
