# Generated by Django 4.2.13 on 2024-05-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_rename_game_type_gametype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='orgaziner',
            new_name='organizer',
        ),
    ]
